### ISSUE TITLE
bad results

### ISSUE THREAD

**Issue by Dan1900** [SiTH-Diffusion/SiTH#14]
When I use your demo picture for test ,the results are good.But,when I use my own pictures,the resutls are bad.I find the back images are error.How can I improve the performance.Thank you!
![企业微信截图_17260510183700](https://github.com/user-attachments/assets/7191fa8b-7414-43b6-bfcf-a3bf5877996b)
![企业微信截图_17261067708510](https://github.com/user-attachments/assets/9598ea5f-4f7f-4546-8e5d-4374ebeced9e)

**Comment by azuxmioy** [comment]
Hi, this might be the problem of failed body fitting.
The default parameters are just used for dataset evaluation. Since there is no parameters that perfectly fit every image, you need to try and play with these parameters in `fit.py`

Also refer to #10 

Also, our method doesn't tackle self-occlusion or difficult poses. Generating textures for these cases is still challenging.

**Comment by Dan1900** [comment]
> Hi, this might be the problem of failed body fitting. The default parameters are just used for dataset evaluation. Since there is no parameters that perfectly fit every image, you need to try and play with these parameters in `fit.py`
> 
> Also refer to #10
> 
> Also, our method doesn't tackle self-occlusion or difficult poses. Generating textures for these cases is still challenging.

Thank you for your reply!I'll try it.
