### ISSUE TITLE
Hand problems

### ISSUE THREAD

**Issue by 12awei** [SiTH-Diffusion/SiTH#16]
你好，作者，我发现重建出来的三维模型手部不佳，而对应的smplx手部模型是良好的。是否可以在重建的时候用保留smplx的手部模型？如果可以的话请给我一些建议。
![image](https://github.com/user-attachments/assets/91b23c8f-9031-428a-b9eb-b0dc356519d5)
![image](https://github.com/user-attachments/assets/b8106531-3ff8-4b2f-a30c-4731ad5a7aaa)

**Comment by azuxmioy** [comment]
Hi. If you need accurate hand reconstruction, I'd say this image is not the correct way to reconstruct hands.

Because hand geometry is highly complex, at least you should make it flat and every finder separated.

<img width="135" alt="Screenshot 2024-09-25 at 10 30 43 AM" src="https://github.com/user-attachments/assets/f62e4174-ebf7-4eda-be49-ce42c24f8887">

**Comment by 12awei** [comment]
谢谢你的回答。我还有一个问题，如果我有一个已经有颜色带纹理的.obj文件，我该怎么做才能转换为a textured mesh with a UV map,就像这样
![image](https://github.com/user-attachments/assets/c7bd9646-7856-4eba-af5c-14b7605da979)

**Comment by 12awei** [comment]
Thank you for your answer. I have another question, if I have an. obj file with color and texture, what should I do to convert it to a textured mesh with a UV map, like this
![image](https://github.com/user-attachments/assets/efc9b84f-9e1d-49cd-8781-bbca605d9d18)

**Comment by azuxmioy** [comment]
Hi, I don't fully understand the question. 
So you only have an obj without UV, only with vertex colors?

If yes, there is no direct way to convert the file. What you need to do is uv unwrapping like in Blender or open3d library. Then you need to generate texture images by querying colors on the original mesh.
