### ISSUE TITLE
Result variation, is it expected?

### ISSUE THREAD

**Issue by hangg7** [SiTH-Diffusion/SiTH#3]
Hi @azuxmioy @SiTH-Diffusion,

Congrats on your great work and thanks for releasing your code and providing a nice demo for us to play with. It is super helpful to understand and use your method!

I manage to get SiTH running on a bunch of my own test images, but it seems like result varies a lot in terms of poses. E.g., for a same person doing different poses from a video, SiTH would work on some "simple" poses (like almost standing, similar to your teaser figure) but fail on other poses. Here is what I meant:

Simple pose works alright
![image](https://github.com/SiTH-Diffusion/SiTH/assets/10098306/95e3078d-526c-47b7-8714-e78c8939b0da)

Harder pose like crossing arm breaks
![image](https://github.com/SiTH-Diffusion/SiTH/assets/10098306/a8c195e4-0a04-4d75-ab53-1d079528189f)

Well but not all the time, here is basically a crossing arm pose but in the opposite direction, it works to some degree
![image](https://github.com/SiTH-Diffusion/SiTH/assets/10098306/9334d91c-dde0-488e-8f8e-16c54e7bfff4)

My question: is this behavior expected? Have you seen anything like this before?

**Comment by hangg7** [comment]
Also FYI, I was trying to use your `hohs/SiTH-diffusion-2000` model but have run into this issue

```bash

```

**Comment by azuxmioy** [comment]
Hi,

> My question: is this behavior expected? Have you seen anything like this before?

This is as expected since the model is finetuned with only 500 3D scans. The bottleneck lies in unseen and challenging poses. 

The sweet spot of our pipeline is front-facing human bodies. Reconstructing humans in challenging poses is not the focus because (1) pose fitting may be challenging and ambiguous, and (2) textures in self-occluded regions cannot be generated. 

We will soon release our training code and you are welcome to analyze the robustness to unseen poses in more detail. 

> Also FYI, I was trying to use your hohs/SiTH-diffusion-2000 model but have run into this issue

The model is located at [https://huggingface.co/hohs/SiTH-diffusion-2000](https://huggingface.co/hohs/SiTH-diffusion-2000)
Perhaps you can download the models and load them locally. 

Thanks!

**Comment by hangg7** [comment]
Thanks for your clarification! That makes sense 😄
