### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by 12awei** [SiTH-Diffusion/SiTH#6]
Will the training code be released？
I want to improve the precision of my hands and ears. Do you have any suggestions？
![image](https://github.com/SiTH-Diffusion/SiTH/assets/95277262/93b24c70-ec41-48c9-b739-640e93215080)
Thank you very much for your work

**Comment by azuxmioy** [comment]
Thanks for the message.

Yes, we plan to release the training code. Due to the semester's end, there are many teaching-related obligations. We couldn't find time to rewrite the training pipeline with the new data format😅 We hope to release them near or after the main conference.

We didn't resolve the side-view artifacts in our CVPR version, but you can still adjust the background color or erosion to reduce them. We also leave this as an open problem for future research🙂

**Comment by azuxmioy** [comment]
FYI the training scripts have been released. We will update the readme soon🙂
